### ISSUE TITLE
renders with crashing

### ISSUE THREAD

**Issue by thisconnect** [Chris927/react-roughviz#6]
This test fails `yarn test, seems to be related to https://github.com/jwilber/roughViz/issues/8

my test only includes the Pie example from https://codesandbox.io/s/react-codesandbox-w7o6u

```js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'

it('renders without crashing', () => {
  const div = document.createElement('div')
  ReactDOM.render(<App />, div)
  ReactDOM.unmountComponentAtNode(div)
})
```

``` 
● renders without crashing

    TypeError: Cannot read property 'ownerDocument' of null

       6 |   const div = document.createElement('div')
       7 |   ReactDOM.render(<App />, div)
    >  8 |   ReactDOM.unmountComponentAtNode(div)
         |            ^
       9 | })
      10 | 

      at Q.draw (node_modules/rough-viz/dist/roughviz.min.js:1:275343)
      at Q.arc (node_modules/rough-viz/dist/roughviz.min.js:1:277832)
      at node_modules/rough-viz/dist/roughviz.min.js:1:343594
          at Array.forEach (<anonymous>)
      at t.value (node_modules/rough-viz/dist/roughviz.min.js:1:343561)
      at t.drawChart (node_modules/rough-viz/dist/roughviz.min.js:1:340811)
      at new t (node_modules/rough-viz/dist/roughviz.min.js:1:339505)
      at node_modules/react-roughviz/src/lib/index.js:11:7
      at commitHookEffectList (node_modules/react-dom/cjs/react-dom.development.js:22030:26)
      at commitPassiveHookEffects (node_modules/react-dom/cjs/react-dom.development.js:22064:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:25392:7)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority$2 (node_modules/react-dom/cjs/react-dom.development.js:12149:10)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:25361:12)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:24251:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23698:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:27103:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:27544:5)
      at node_modules/react-dom/cjs/react-dom.development.js:27649:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:24433:12)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:27648:5)
      at Object.<anonymous> (src/App.test.tsx:8:12)

```

**Comment by Chris927** [comment]
Hi @thisconnect, thanks for reporting this.

It seems you cannot run this type of test, due to how [roughViz](https://github.com/jwilber/roughViz) accesses the environment.

I've added an integration test, that demonstrates how you could do testing, see the previous commit.

This issue cannot be fixed here, I'm therefore closing it.

**Comment by thisconnect** [comment]
thanks
